# Generated by Django 3.2.9 on 2022-12-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('kelompok', models.CharField(max_length=255)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.canteen')),
            ],
        ),
    ]
