# Generated by Django 3.2.9 on 2022-09-28 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('on_click_url', models.URLField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.canteen')),
            ],
        ),
    ]
