# Generated by Django 3.2.9 on 2022-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='is_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
