name: Test

on:
  push:
    branches-ignore:
      - template
  pull_request:
    branches-ignore:
      - template

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ github.job }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Collect static files
        run: python manage.py collectstatic --no-input
      - name: Run unit tests
        run: |
          coverage run --parallel --include="./*" --omit="manage.py,go_canteen/*" \
          manage.py test --exclude-tag=functional
